services:
  bot:
    image: ghcr.io/go-tiger/gt-studio-bot:latest
    container_name: gt-studio-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot.db:/app/bot.db
    environment:
      - NODE_ENV=production
